name: Deploy docs
on:
  push:
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install -r requirements/project.txt
      - name: Build site
        run: mkdocs build
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/deploy'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: site
          commit_message: 'Generate docs: '
